### ISSUE TITLE
Integrating additional plugin

### ISSUE THREAD

**Issue by oliverkidd** [nshenderov/strapi-plugin-ckeditor#101]
I have tried for days to integrate a plugin to this package, but it does not seem to be working. I want to try and add in support for math/chem equations using the following rpm package (https://github.com/isaul32/ckeditor5-math).

I have managed to install and adjust the config, but the custom plugin is not being loaded into the config. Any pointers?

Maybe this could be added as a feature - it is extremely useful.

**Comment by oliverkidd** [comment]
Thanks! Where is the myCustom.plugin syntax coming from? I managed to do the above but the plugin was never accessible from the CKEditor5 window object?

**Comment by lamuertepeluda** [comment]
> Thanks! Where is the myCustom.plugin syntax coming from? I managed to do the above but the plugin was never accessible from the CKEditor5 window object?

It's a naming convention from CKEditor plugins which use [Webpack DLL plugin](https://webpack.js.org/plugins/dll-plugin/) for being plugged in to the main editor module.

I implemented (basically for testing the capabilities) a [custom widget following the tutorial](https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-a-block-widget.html) and I started with [their packaging tool](https://github.com/ckeditor/ckeditor5-package-generator) which is still beta atm, and sets up a project that uses Webpack DLL plugin + their conventions (which I advice to follow). 

In my experience, at least using TypeScript, neither approach worked straight away. But hammering a bit the project structure and declaring some globals such as a bit, you get out with a working plugin.

**Comment by oliverkidd** [comment]
Thanks I'll check it out!

**Comment by iamtun** [comment]
> Thanks I'll check it out!
Hi @oliverkidd, i have same issue with you. How to fix this? Can you help me?

**Comment by iamtun** [comment]
@lamuertepeluda Hello. I fixed the problem above but I want to add a cdn at the top to format the plugin's output. I have found the answer but haven't found it yet. Can you help me? "How to add a cdn to the head tag". 
Ex: https://jsfiddle.net/isaul32/qktj9h7x/

**Comment by lamuertepeluda** [comment]
> @lamuertepeluda Hello. I fixed the problem above but I want to add a cdn at the top to format the plugin's output. I have found the answer but haven't found it yet. Can you help me? "How to add a cdn to the head tag". 
> 
> Ex: https://jsfiddle.net/isaul32/qktj9h7x/

Hello @iamtun, I'm not sure the CDN is the correct approach here, since the way strapi adds dependencies is via yarn/npm. 
Once you install a package, you should import it into the `src/admin/app.tsx` file (I use the strapi TypeScript template, you will have `app.js` or `app.jsx` if you use plain JavaScript). Now you have to rebuild the frontend. Check also my first answer to this thread.

If you cannot download your plugin from npm, then you can create a `plugins` folder in the strapi project root directory and put your plugin code there in a subfolder and modify the config/plugin.(ts|js) file to resolve your plugin from the root plugins sub folder (*check this repository development guide for examples*).

Have also a look to https://docs.strapi.io/dev-docs/admin-panel-customization for how the admin panel customization works.

**Comment by iamtun** [comment]
Thanks for your feedback. After hours of searching, I solved my problem another way add `import 'mathjax/es5/tex-svg-full.js'` in `admin/src/app` .  Problem solved!

**Comment by exniwe** [comment]
@lamuertepeluda @iamtun could anyone of you maybe give a quick guide on how to add plugins to your ckeditor in strapi? I followed the instructions in this thread here for hours, but it didn't work

**Comment by lamuertepeluda** [comment]
@exniwe all I did and I know is described in this thread or in #100. Is it perhaps some differences in our setups that prevent you from achieving the result?

**Comment by exniwe** [comment]
@lamuertepeluda Okay I did what you described in #100 and it works. But now I am trying to add this [math plugin](https://github.com/isaul32/ckeditor5-math) following [your instruction](https://github.com/nshenderov/strapi-plugin-ckeditor/issues/101#issuecomment-1514850668), but I always get "ckeditor-duplicated-modules" error. So how would you add the math plugin?

**Comment by lamuertepeluda** [comment]
@exniwe 
1. make sure you are installing [your plugin version](https://github.com/isaul32/ckeditor5-math/tags) that matches the CKeditor version in this strapi plugin (was 36.0.0, if I am not wrong - pls check the [package.json](https://github.com/nshenderov/strapi-plugin-ckeditor/blob/master/package.json) - I also have a PR open for upgrading, which in turn needs to be updated to 38.0.1). Having different CKEditor runtime versions can lead to that error.
2. check that the version of the plugin you will choose is [DLL-compatible](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds.html). Not all CKEditor plugins were ported to the relatively new DLL build of CKEditor, which makes it easy to have modular plugins.

**Comment by exniwe** [comment]
Okay, thanks @lamuertepeluda The installation as described by you worked. However, the latex expressions are not yet formatted. So, for example, when I enter an expression like x=\frac{-b\pm\sqrt{b^2-4ac}}{2a} in the input field of the math plugin, it is displayed unformatted. The documentation says that you can adjust the plugin options here, but I don't know where exactly in the plugin itself you can do that.

**Comment by lamuertepeluda** [comment]
Hi @exniwe I don't know in the case on the plugin you are trying to add, since I never used, but generally speaking plugin options have to be provided via config using a declarative syntax.  
As an example, consider how the [link plugin options](https://ckeditor.com/docs/ckeditor5/latest/features/link.html#configuration) are provided in the [base config file](https://github.com/nshenderov/strapi-plugin-ckeditor/blob/master/admin/src/components/Input/CKEditor/configs/base.js#L354). Hope it helps.

**Comment by iamtun** [comment]
> Okay, thanks @lamuertepeluda The installation as described by you worked. However, the latex expressions are not yet formatted. So, for example, when I enter an expression like x=\frac{-b\pm\sqrt{b^2-4ac}}{2a} in the input field of the math plugin, it is displayed unformatted. The documentation says that you can adjust the plugin options here, but I don't know where exactly in the plugin itself you can do that?

Hi @exniwe, don't know if you have `mathjax` installed? If not then install mathJax and import 'mathjax/es5/tex-svg-full.js' in app.js. It works for my case

**Comment by kulak91** [comment]
Hey guys!
I have a problem importing custom plugins (mine for testing or existing markdown gfm) into the `/src/admin/app.tsx`. The issue is in this line: 
<img width="808" alt="image" src="https://github.com/nshenderov/strapi-plugin-ckeditor/assets/49899827/8bb4ba75-f332-47b1-a760-db756dc0d6ff">
it says that CKEditor is undefined.
<img width="947" alt="image" src="https://github.com/nshenderov/strapi-plugin-ckeditor/assets/49899827/3175c869-7086-4ac1-8ee5-6df34c40a615">
<img width="352" alt="image" src="https://github.com/nshenderov/strapi-plugin-ckeditor/assets/49899827/258b8366-c439-49c9-a211-823503cca9cb">
However if i import code directly into the ckeditor.ts config it works..
<img width="929" alt="image" src="https://github.com/nshenderov/strapi-plugin-ckeditor/assets/49899827/90d1f5cc-bd12-4a64-894d-95b42f9031f8">
Any idea how to fix this?
It also works in this same file if i will paste full code of the plugin before defining CKEditor5, but changing CKEditor5 to window.CKEditor5. (it works like this only in ckeditor.ts)
<img width="1169" alt="image" src="https://github.com/nshenderov/strapi-plugin-ckeditor/assets/49899827/f9b766f6-c3ba-48c2-86b0-650f35112dc9">

**Comment by tshmieldev** [comment]
When I import the plugin, I instantly get duplicate ckeditor error, on two separate plugins, all I want is some math in my editor...
