### ISSUE TITLE
Upgrade to latest CKEditor 5 (37.1.0+)

### ISSUE THREAD

**Issue by lamuertepeluda** [nshenderov/strapi-plugin-ckeditor#102]
Hi there,

[a new CKEditor version](https://github.com/ckeditor/ckeditor5/releases/tag/v37.1.0) as been released today.

The latest 37.x is all written in TypeScript, so hopefully dealing with typings should be less annoying.

They are also going to release soon [a CKEditor package generator tool](https://github.com/ckeditor/ckeditor5-package-generator) for allowing people to further customize the editor, e.g. with custom plugins and widgets. This will be compatible with 37.x

Is there any plan to upgrade this plugin with the latest CKEditor version anytime soon?

**Comment by EsGeh** [comment]
I created a [fork](https://github.com/EsGeh/strapi-plugin-ckeditor) in order to be able to use latest ckeditor versions and the latest strapi version.

[Pull Request](https://github.com/nshenderov/strapi-plugin-ckeditor/pull/117)

Please consider upvoting on the corresponding pull request.
Maybe it helps.
