### ISSUE TITLE
Unsure which plugin to use

### ISSUE THREAD

**Issue by boazpoolman** [nshenderov/strapi-plugin-ckeditor#170]
Don't know if this is the right place for this question, but which plugin should I use and why?

Yours: https://market.strapi.io/plugins/@_sh-strapi-plugin-ckeditor

Or the official one: https://market.strapi.io/plugins/@ckeditor-strapi-plugin-ckeditor

**Comment by nshenderov** [comment]
Well, which plugin to use is entirely up to you. This plugin was created because the previous community one was abandoned, and it was released before CKEditor became an official Strapi partner. Internally, it uses the same official ckeditor-react package.

From my perspective, since its release, the CKEditor team hasn’t really maintained their plugin well enough, and it lacks many important features (I would have archived this repo otherwise). This plugin, on the other hand, provides:
- Rich configuration through a config file
- Different UI translations and i18n support
- Dark theme support
- Custom plugin support

Also, unlike the official one, this plugin doesn't rely on a CDN for the CKEditor package.

**Comment by boazpoolman** [comment]
Got it! Thanks for the explanation.
I can make a well informed decision now.
