### ISSUE TITLE
Purple color on the menu and html editor

### ISSUE THREAD

**Issue by tdserviceco** [nshenderov/strapi-plugin-ckeditor#3]
I know you wrote how to change the color.. but how do I return it to how CKeditor has its colour scheme? 
is there a fast and easy way?

**Comment by nshenderov** [comment]
The only way is to change the variables used for light and dark theme to default colors https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html

**Comment by zak-eddingtonPOP** [comment]
Currently, there doesn't seem to be a way to override the entire purple theme by updating the variables alone since they are not being scoped to :root. For example, the link tooltip is outside of .ck-editor__styled__container so it is always purple.

As far as I can tell, there is no way to add a data-theme attribute on the html element of Strapi to use the light/dark themes.

It would be better to set the default theme to the default CKEditor theme (or the light theme), and add a config option to easily swap themes instead of manually including every css variable.

**Comment by nshenderov** [comment]
@tdserviceco @zak-eddingtonPOP check new version
