### ISSUE TITLE
Is it possible to toggle between HTML output and Markdown output?

### ISSUE THREAD

**Issue by hieuhlc** [nshenderov/strapi-plugin-ckeditor#36]
I have read through the CKEditor document and look like we can only define one output for the editor from the start. I think this feature is super nice to have

**Comment by nshenderov** [comment]
@hieuhlc Hi, you can toggle it via configuration in plugins.js, but since strapi v4.4.0 there are custom fields and [the official ckeditor plugin for strapi](https://market.strapi.io/plugins/@ckeditor-strapi-plugin-ckeditor) is currently developing may be you should write it to [them](https://github.com/ckeditor/strapi-plugin-ckeditor).

**Comment by kareem-g** [comment]
YEA! just all the following LoC in your Editor config of CKEditor 5 Plugin `plugins.js` or `plugins.ts` :

`
    ckeditor: {
    enabled: true, config: {
      editor: {
        removePlugins: [""],
        }
    }
 }
`

**Comment by hieuhlc** [comment]
I had to define a custom field for markdown content and used a specific markdown editor for that field
