### ISSUE TITLE
How to lazyload images and change paths

### ISSUE THREAD

**Issue by Zharkan** [nshenderov/strapi-plugin-ckeditor#6]
It's a very nice plugin but my client has an image heavy website (photograph) so I would like to know if it's possible to change path for uploaded media ? Currently CKEditor ouputs the image with relative path so I'd like to be able to output this :

https://api.example.org + path

Also is it possible to lazyload images, at the very least add a loading="lazy" ?

**Comment by nshenderov** [comment]
@Zharkan If you use default upload provider and you want prefix url with api path you need to modify api.js file in ``config/api.js`` and add baseURL, something like this:
```js
module.exports = ({ env }) => ({
  rest: {
    defaultLimit: 25,
    maxLimit: 100,
    withCount: true,
  },
  baseURL:env('PUBLIC_URL', 'http://localhost:1337')
});
```
About loading lasy - you can modify html tags through source mode in the editor, but in order to be able to add loading tag you need to add in plugin config some configurations, something like this:
``config/plugins.js``
```js
module.exports = ({ env }) => ({
    ckeditor: {
      enabled: true,
      config: {
        plugin: {},
        editor: {
          htmlSupport: {
            allow: [
                {
                  name: 'img',
                  attributes: {
                      sizes:true,
                      loading:true,
                  }
                },
            ]
        },
        },
      },
    },
  });
```
After that you can add loading and sizes attributes in the source mode
![2022-05-17 151412](https://user-images.githubusercontent.com/103522779/168808575-04199ec9-62f5-4e30-9fd7-44fdd93a6fcb.jpg)

![2022-05-17 151512](https://user-images.githubusercontent.com/103522779/168808650-4d94dedc-771e-4092-8ed4-99602dcb6c90.jpg)

**Comment by Zharkan** [comment]
That is perfect, thank you for this ! I'm closing this then.
