### ISSUE TITLE
2.0 not working for me

### ISSUE THREAD

**Issue by sleeporsmile** [nshenderov/strapi-plugin-ckeditor#62]
I just updated the version to v2 and removed unnecessary config in plugins.js according to documentation and rebuild, . I've been tried adding the config file ckeditor.txt, no help. v1.1.3 works fine. 
db: sqlite
node: v16, v18
npm: v6, v8
@_sh/strapi-plugin-ckeditor: v2

**Comment by nshenderov** [comment]
@sleeporsmile Could you please provide what your plugins.js and package.json look like and what error message did you get?

**Comment by sleeporsmile** [comment]
> @sleeporsmile Could you please provide what your plugins.js and package.json look like and what error message did you get?

Actually, it doesn't even work in a new strapi project. No plugins.js, no error, just default editor. 
Macbook m1 pro
node: v18.13.0
npm: v8.19.3
`{
  "name": "my-project",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.1",
    "@strapi/plugin-i18n": "4.6.0",
    "@strapi/plugin-users-permissions": "4.6.0",
    "@strapi/strapi": "4.6.0",
    "better-sqlite3": "^8.0.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "cc89b33a-b254-4ff0-a4f8-e8e10721f6c4"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
`

**Comment by nshenderov** [comment]
@sleeporsmile Since version 2 this plugin works through custom field API it doesn't change the default editor anymore instead it adds a new custom field https://youtu.be/hIKfvLzN6VI

**Comment by sleeporsmile** [comment]
> @sleeporsmile Since version 2 this plugin works through custom field API it doesn't change the default editor anymore instead it adds a new custom field https://youtu.be/hIKfvLzN6VI

Now I understand, thanks. This is missing from the documentation. How do I migrate from 1.1.3 to 2.0. I have too many entries

**Comment by nshenderov** [comment]
@galago You can still use 1.1.3 version if you wish but custom fields are the way strapi team decided to move further about plugins. You can manually transform your schema from use a default rich field to a custom field or write some migration script it is all up to you. Also, note that this is not an official plugin and there is no some big team behind it, this plugin doesn't maintain eather strapi or ckeditor, it is more like a community plugin so feel free to discuss and contribute. I also want to note that you can use 1.1.3 with locally installed 2.0.0 following [contributing guide](https://github.com/nshenderov/strapi-plugin-ckeditor/edit/master/README.md#-contributing) because these versions use different id`s ("ckeditor" and "ckeditor5"), so you can not only have default rich text fields working through ckeditor5 but also a new custom field along with them

**Comment by Bradzer** [comment]
> @sleeporsmile Since version 2 this plugin works through custom field API it doesn't change the default editor anymore instead it adds a new custom field https://youtu.be/hIKfvLzN6VI

It is probably a good think to make it clearly appear in the README.
