### ISSUE TITLE
"Media library" image is wrapped in p tag

### ISSUE THREAD

**Issue by maslomeister** [nshenderov/strapi-plugin-ckeditor#73]
Hi there, I understand that this might by not related to this plugin at all,  but there's a problem with **media library** and local provider

When i add image using **media library** button, it looks like this in html
```html
<p>
    <img src="http://localhost:1337/uploads/preview_108f3babee.jpg" alt="preview">
</p>
```

and it's semantically incorrect and doesn't have an "image" class also

But if i press "**insert media"** and upload media library directly it now works as expected
```html
<figure class="image image_resized" style="width:50%;">
    <img alt="benjamin-ong-amsm5416cjo-unsplash.jpg" src="http://localhost:1337/uploads/benjamin_ong_amsm5416cjo_unsplash_eca04770ef.jpg">
</figure>
```
(yes, it's two different images)

Is there a way to fix **media library** to work like **insert media**?

And no, i can't simply use **insert media** because there's a lot of media, i upload it manually to specific folder and then select it with *media library** and **insert media** simply uploads media to the root folder, which is no go for me :(

**Comment by maslomeister** [comment]
After i wrote this and though about for a bit, i understood that **media library** is for media (duh, should've been obvious) and **insert image** is for images, but my question now is

Is it possible to insert image from media library so it would use localhost in development and production url in production?

**Comment by nshenderov** [comment]
@maslomeister Hi, switching between dev and prod and all about the media in common is not the responsibility of this plugin, you just have access to strapi's media library inside it and nothing else. Since you upload an image to strapi, paste it to ckeditor, and save it, it is stored in your database as an HTML string and if you switch your host address, it won't switch it inside that string. I personally prefer to use s3 bucket for media than store them locally also because of this.

**Comment by maslomeister** [comment]
Thanks for response, yeah, you are correct about this not being plugin related, closing.
